version: '3.8'
services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    entrypoint: ./docker-entrypoint.sh
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development

volumes:
  node_modules:
